name: CI

on:
  push:
    tags:
    # "v" で始まる Tag 名の push だけをトリガーの対象に (e.g., "v0.0.2")
    - 'v*'

jobs:
  # Windows 用の job 定義
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm install
      run: npm install
    - name: build application
      run: npm run build:win
    - name: create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          dist/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Actions for Discord
      uses: sarisia/actions-status-discord@v1.8.1
      if: always()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        status: ${{ job.status }}